source "https://rubygems.org"

ruby "3.2.3"  # Updated Ruby version

# Rails framework
gem "rails", "~> 7.1.3", ">= 7.1.3.2"

# Asset pipeline for Rails
gem "sprockets-rails"

# Database for Active Record
gem "sqlite3", "~> 1.4"

# Web server
gem "puma", ">= 5.0"

# JavaScript with ESM import maps
gem "importmap-rails"

# Hotwire's SPA-like page accelerator
gem "turbo-rails"

# Hotwire's modest JavaScript framework
gem "stimulus-rails"

# Build JSON APIs with ease
gem "jbuilder"

# Action Cable adapter for Redis
# gem "redis", ">= 4.0.1"

# Cross-origin resource sharing
gem "rack-cors"

# Kredis for higher-level data types in Redis
# gem "kredis"

# Active Model has_secure_password
# gem "bcrypt", "~> 3.1.7"

# Zoneinfo files for time zone support
gem "tzinfo-data", platforms: %i[ jruby ]

gem 'tzinfo-data'

# Bootsnap for boot time optimization
gem "bootsnap", require: false

group :development, :test do
  # Debugging with the debug gem
  gem "debug", platforms: %i[ mri ]
end

group :development do
  # Console on exceptions pages
  gem "web-console"

  # Speed badges
  # gem "rack-mini-profiler"

  # Speed up commands
  # gem "spring"
end

group :test do
  # System testing
  gem "capybara"
  gem "selenium-webdriver"
end
